export const AUTHENTICATION_SCREEN = 'AUTHENTICATION_SCREEN';
export const RESET_PASSWORD_SCREEN = 'RESET_PASSWORD_SCREEN';
export const REGISTRATION_SCREEN = 'REGISTRATION_SCREEN';
export const FIRST_QUIZ_SCREEN = 'FIRST_QUIZ_SCREEN';
export const SECOND_QUIZ_SCREEN = 'SECOND_QUIZ_SCREEN';
export const QUIZ_DONE_SCREEN = 'QUIZ_DONE_SCREEN';
export const CONSULTANT_SELECTING_SCREEN = 'CONSULTANT_SELECTING_SCREEN';
export const YOUR_PSYCH_SCREEN='YOUR_PSYCH_SCREEN';
export const RECORD_PSYCH_SCREEN='RECORD_PSYCH_SCREEN';
export const CHOOSE_TIME_RECORD_PSYCH_SCREEN = 'CHOOSE_TIME_RECORD_PSYCH_SCREEN';
export const PAYMENT_SCREEN = 'PAYMENT_SCREEN';
export const PAYMENT_WIDGET = 'PAYMENT_WIDGET';
export const ALL_CONSULTATION_SCREEN = 'ALL_CONSULTATION_SCREEN';
export const CONSULTATION_SCREEN = 'CONSULTATION_SCREEN';
export const CHAT_SCREEN = 'CHAT_SCREEN';
export const CONS_CHAT_SCREEN = 'CONS_CHAT_SCREEN';
export const IMAGE_FULL_SCREEN = 'IMAGE_FULL_SCREEN';

export const MAIN_SCREEN = 'MAIN_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';

export const PROFILE_STACK = 'PROFILE_STACK';

export const SECOND_QUIZ_STACK = 'SECOND_QUIZ_STACK';

export const CONSULTANT_SELECTING_STACK = 'CONSULTANT_SELECTING_STACK';

export const ALL_CONSULTATION_STACK = 'ALL_CONSULTATION_STACK';
export const AUTHENTICATION_STACK = 'AUTHENTICATION_STACK';
export const MAIN_STACK = 'MAIN_STACK';
